
import script.script as tc
import script.v3_7 as tc1
import script.v3_8 as tc2
import script.v3_9 as tc3
import script.v3_10 as tc4
import script.v3_11 as tc5
import script.v3_12 as tc6
import script.v3_13 as tc7
import script.v3_14 as tc8

testcase = [
    # tc.PersonalAccessToken, 
    tc.OrganizationBasicData, 
    tc.RepoData, 
    tc.SampleBranch,  
    tc.PullRequest,  
    tc.LFSData, 
    tc.Release,  
    tc.Package, 
    tc.Issue, 
    tc.Project,
    tc.Wiki, 
    tc.Webhook, 
    tc.PreReceiveHook,
    tc.RepoPages,
    tc.OrganizationPackages,
    tc.OrganizationPackages2,
    tc.RepoPackage,  
    tc.OrganizationSecurityAlerts, 
    tc.RepoCodeScanning,  
    tc.RepoDependabot, 
    tc.RepoSecretScanning, 
    # tc.OrganizationRunners, 
    # tc.RepoRunner, 
    # tc.OrgRunner, 
    # tc.EnterpriseRunner, 
    # tc.OrganizationEmpty,
    tc.Gist, 
    tc.NewUser, 
    tc.TestEmail, 
    tc.ManagementConsoleSetting, 
    # tc.testdebug, 
]

testcase3_7 = [
    # tc1.PersonalAccessToken, 
    tc1.OrganizationBasicData, 
    tc1.RepoData, 
    tc1.SampleBranch,  
    tc1.PullRequest,  
    tc1.LFSData, 
    tc1.Release,  
    tc1.Package, 
    tc1.Issue, 
    tc1.Project,
    tc1.Wiki, 
    tc1.Webhook, 
    tc1.PreReceiveHook,  
    tc1.OrganizationSecurityAlerts, 
    tc1.RepoCodeScanning,  
    tc1.RepoDependabot, 
    tc1.RepoSecretScanning, 
    # tc1.OrganizationRunners, 
    # tc1.RepoRunner, 
    # tc1.OrgRunner, 
    # tc1.EnterpriseRunner, 
    # tc1.OrganizationEmpty, 
    tc1.Gist, 
    tc1.NewUser, 
    tc1.TestEmail, 
    tc1.ManagementConsoleSetting, 
    # tc1.testdebug, 
]

testcase3_8 = [
    # tc2.PersonalAccessToken, 
    tc2.OrganizationBasicData, 
    tc2.RepoData, 
    tc2.SampleBranch,  
    tc2.PullRequest,  
    tc2.LFSData, 
    tc2.Release,  
    tc2.Package, 
    tc2.Issue, 
    tc2.Project,
    tc2.Wiki, 
    tc2.Webhook, 
    tc2.PreReceiveHook,  
    tc2.OrganizationSecurityAlerts, 
    tc2.RepoCodeScanning,  
    tc2.RepoDependabot, 
    tc2.RepoSecretScanning, 
    # tc2.OrganizationRunners, 
    # tc2.RepoRunner, 
    # tc2.OrgRunner, 
    # tc2.EnterpriseRunner, 
    # tc2.OrganizationEmpty, 
    tc2.Gist, 
    tc2.NewUser, 
    tc2.TestEmail, 
    tc2.ManagementConsoleSetting, 
    # tc2.testdebug, 
]

testcase3_9 = [
    # tc3.PersonalAccessToken, 
    tc3.OrganizationBasicData, 
    tc3.RepoData, 
    tc3.SampleBranch,  
    tc3.PullRequest,  
    tc3.LFSData, 
    tc3.Release,  
    tc3.Package, 
    tc3.Issue, 
    tc3.Project,
    tc3.Wiki, 
    tc3.Webhook, 
    tc3.PreReceiveHook,  
    tc3.OrganizationSecurityAlerts, 
    tc3.RepoCodeScanning,  
    tc3.RepoDependabot, 
    tc3.RepoSecretScanning, 
    # tc3.OrganizationRunners, 
    # tc3.RepoRunner, 
    # tc3.OrgRunner, 
    # tc3.EnterpriseRunner, 
    # tc3.OrganizationEmpty, 
    tc3.Gist, 
    tc3.NewUser, 
    tc3.TestEmail, 
    tc3.ManagementConsoleSetting, 
    # tc3.testdebug, 
]

testcase3_10 = [
    # tc4.PersonalAccessToken, 
    tc4.OrganizationBasicData, 
    tc4.RepoData, 
    tc4.SampleBranch,  
    tc4.PullRequest,  
    tc4.LFSData, 
    tc4.Release,  
    tc4.Package, 
    tc4.Issue, 
    tc4.Project,
    tc4.Wiki, 
    tc4.Webhook, 
    tc4.PreReceiveHook,  
    tc4.OrganizationSecurityAlerts, 
    tc4.RepoCodeScanning,  
    tc4.RepoDependabot, 
    tc4.RepoSecretScanning, 
    # tc4.OrganizationRunners, 
    # tc4.RepoRunner, 
    # tc4.OrgRunner, 
    # tc4.EnterpriseRunner, 
    # tc4.OrganizationEmpty, 
    tc4.Gist, 
    tc4.NewUser, 
    tc4.TestEmail, 
    tc4.ManagementConsoleSetting, 
    # tc4.testdebug, 
]

testcase3_11 = [
    # tc5.PersonalAccessToken, 
    tc5.OrganizationBasicData, 
    tc5.RepoData, 
    tc5.SampleBranch,  
    tc5.PullRequest,  
    tc5.LFSData, 
    tc5.Release,  
    tc5.Package, 
    tc5.Issue, 
    tc5.Project,
    tc5.Wiki, 
    tc5.Webhook, 
    tc5.PreReceiveHook,  
    tc5.OrganizationSecurityAlerts, 
    tc5.RepoCodeScanning,  
    tc5.RepoDependabot, 
    tc5.RepoSecretScanning, 
    # tc5.OrganizationRunners, 
    # tc5.RepoRunner, 
    # tc5.OrgRunner, 
    # tc5.EnterpriseRunner, 
    # tc5.OrganizationEmpty, 
    tc5.Gist, 
    tc5.NewUser, 
    tc5.TestEmail, 
    tc5.ManagementConsoleSetting, 
    # tc5.testdebug, 
]

testcase3_12 = [
    # tc6.PersonalAccessToken, 
    tc6.OrganizationBasicData, 
    tc6.RepoData, 
    tc6.SampleBranch,  
    tc6.PullRequest,  
    tc6.LFSData, 
    tc6.Release,  
    tc6.Package, 
    tc6.Issue, 
    tc6.Project,
    tc6.Wiki, 
    tc6.Webhook, 
    tc6.PreReceiveHook,  
    tc6.OrganizationSecurityAlerts, 
    tc6.RepoCodeScanning,  
    tc6.RepoDependabot, 
    tc6.RepoSecretScanning, 
    # tc6.OrganizationRunners, 
    # tc6.RepoRunner, 
    # tc6.OrgRunner, 
    # tc6.EnterpriseRunner, 
    # tc6.OrganizationEmpty, 
    tc6.Gist, 
    tc6.NewUser, 
    tc6.TestEmail, 
    tc6.ManagementConsoleSetting, 
    # tc6.testdebug, 
]

testcase3_13 = [
    # tc7.PersonalAccessToken, 
    tc7.OrganizationBasicData, 
    tc7.RepoData, 
    tc7.SampleBranch,  
    tc7.PullRequest,  
    tc7.LFSData, 
    tc7.Release,  
    tc7.Package, 
    tc7.Issue, 
    tc7.Project,
    tc7.Wiki, 
    tc7.Webhook, 
    tc7.PreReceiveHook,  
    tc7.OrganizationSecurityAlerts, 
    tc7.RepoCodeScanning,  
    tc7.RepoDependabot, 
    tc7.RepoSecretScanning, 
    # tc7.OrganizationRunners, 
    # tc7.RepoRunner, 
    # tc7.OrgRunner, 
    # tc7.EnterpriseRunner, 
    # tc7.OrganizationEmpty, 
    tc7.Gist, 
    tc7.NewUser, 
    tc7.TestEmail, 
    tc7.ManagementConsoleSetting, 
    # tc7.testdebug, 
]

testcase3_14 = [
    tc8.OrganizationBasicData, 
    tc8.RepoData, 
    tc8.SampleBranch,  
    tc8.PullRequest,  
    tc8.LFSData, 
    tc8.Release,  
    tc8.Package, 
    tc8.Issue, 
    tc8.Project,
    tc8.Wiki, 
    tc8.Webhook, 
    tc8.PreReceiveHook,  
    tc8.OrganizationSecurityAlerts, 
    tc8.RepoCodeScanning,  
    tc8.RepoDependabot, 
    tc8.RepoSecretScanning, 
    tc8.Gist, 
    tc8.NewUser, 
    tc8.TestEmail, 
    tc8.ManagementConsoleSetting, 
]
